apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-config
data:
  application.properties: |
    spring.datasource.url={{ .Values.env.DB_URL }}
    spring.datasource.username={{ .Values.env.DB_USERNAME }}
    spring.datasource.password={{ .Values.env.DB_PASSWORD }}
