{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  host: {{ include "auth-service.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- end }}
