{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gatewayName }}
  http:
    - route:
        - destination:
            host: {{ include "auth-service.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      retries:
        attempts: {{ .Values.istio.retries.attempts }}
        perTryTimeout: {{ .Values.istio.retries.perTryTimeout }}
        retryOn: {{ .Values.istio.retries.retryOn }}
{{- end }}
