apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  password: {{ .Values.auth.adminPassword | quote }}
---
{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}