apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: platform-authz
  namespace: apps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: platform
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      when:
        - key: request.auth.claims[tenant_id]
          notValues: [""]
