{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  labels:
    app: mysql
type: Opaque
stringData:
  mysql-root-password: {{ .Values.auth.rootPassword | quote }}
  mysql-user: {{ .Values.auth.user | quote }}
  mysql-password: {{ .Values.auth.password | quote }}
  mysql-database: {{ .Values.auth.database | quote }}
{{- end }}