apiVersion: v2
name: pbx-core
description: PBX Core Helm chart (parent)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 1.0.0
    repository: file://charts/mysql
    import-values: []
    
  - name: redis
    version: 1.0.0
    repository: file://charts/redis

  - name: kafka
    version: 1.0.0
    repository: file://charts/kafka
