apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
  - ../../base
  - ../../components/istio-gateway
  - ../../components/istio-security

patches:
  - target:
      kind: RequestAuthentication
      name: platform-jwt
    patch: |
      - op: replace
        path: /spec/jwtRules/0/issuer
        value: "https://auth.dev.localhost/realms/platform"
      - op: replace
        path: /spec/jwtRules/0/jwksUri
        value: "https://auth.dev.localhost/realms/platform/protocol/openid-connect/certs"
